### ISSUE TITLE
Create Menu Page US-5 [ALTA] - Crear una menu page.

### ISSUE THREAD

**Issue by Gaaston12** [pgPilfs/proyecto-2b-g2b#5]
COMO usuario 
QUIERO poder navegar por todas las herramientas que me bringa la pagina
PARA poder tener un control de los movimientos, del estado de la cuenta, etc.

Criterios:
- Poder ver el saldo de las cuentas.
- Enviar pesos a otra cuentas.
- Que sea una view solamente para cuando estas logueado.
- Cerrar sesion.
- No debe mostrarse el menu si el usuario no está logeado.

**Comment by JuanDubowez** [comment]
Agrego nuevo criterio de aceptacion
